### ISSUE TITLE
No implicit vectorization

### ISSUE THREAD

**Issue by ojessen** [ojessen/ojUtils#2]
ifelseC(p>0,0,p) throws an error with length(p)>1, as the size of the vectors is different.

**Comment by clbieganek** [comment]
I noticed this also. It would be nice if `ifelseC` automatically recycled/vectorized scalar entries for the `yes` and `no` arguments.

**Comment by ojessen** [comment]
Closed in V 0.1.1, to be released on CRAN eventually.
